# Generated by Django 5.0 on 2025-09-09 17:19

import tarefas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('descricao', models.CharField(max_length=120)),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('concluida', models.BooleanField()),
                ('foto', models.FileField(blank=True, null=True, upload_to=tarefas.models.upload_foto)),
            ],
        ),
    ]
